spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver

swisscansatapi:
  cors:
    allowedOrigins:
      - "http://localhost:63342"