spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver

swisscansatapi:
  auth:
    user: ${API_USER}
    password: ${API_PASSWORD}
  cors:
    allowedOrigins:
      - ${CORS_ALLOWED_ORIGINS}