spring:
  datasource:
    url: jdbc:mysql://localhost:3306/divtechx
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver

swisscansatapi:
  auth:
    user: admin
    password: admin
  cors:
    allowedOrigins:
      - "*"
